/**
 * Site-wide identity and configuration.
 * Edit this file to change the name, tagline, and social links everywhere.
 */

export const site = {
  name: "Daniel Cai",
  fullName: "Daniel (Haofan) Cai",
  role: "Data Science & Economics @ Northwestern",
  // one or two sentences, shown on the homepage under the name
  tagline:
    "I build models and pipelines that turn messy real-world data — energy queues, housing listings, legal contracts — into decisions people can act on.",
  url: "https://danielchf2006.github.io",
  email: "danielcai2029@u.northwestern.edu",
  location: "Evanston, IL",
  // dropped into /public/resume/ — see that folder's README
  resumePath: "/resume/Daniel-Cai-Resume.pdf",
  // portrait in the homepage hero. Currently a hand-made pixel avatar
  // (generated by tools/portrait.py). Swap for a real photo any time — just
  // drop it in /public/images/profile/ and point here. "" = placeholder tile.
  portrait: "/images/profile/daniel.png",
  // the CRT boot-sequence entry animation (src/components/IntroOverlay.astro)
  intro: {
    enabled: true,
    // true: plays once per browser session. false: every page load.
    showOncePerSession: true,
  },
} as const;

export type SocialLink = {
  label: string;
  href: string;
  // pixel icon name — see src/components/PixelIcon.astro
  icon: "mail" | "github" | "linkedin";
};

export const socials: SocialLink[] = [
  { label: "Email", href: `mailto:danielcai2029@u.northwestern.edu`, icon: "mail" },
  { label: "GitHub", href: "https://github.com/Danielchf2006", icon: "github" },
  { label: "LinkedIn", href: "https://www.linkedin.com/in/daniel-cai-5b0706261/", icon: "linkedin" },
];

export type NavItem = { label: string; href: string };

export const nav: NavItem[] = [
  { label: "About", href: "/" },
  { label: "Experience", href: "/experience" },
  { label: "Projects", href: "/projects" },
  { label: "Skills", href: "/skills" },
];
